# Generated by Django 3.2.9 on 2021-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=500)),
                ('fecha_nacimiento', models.DateField()),
                ('respuesta1', models.CharField(max_length=500)),
                ('respuesta2', models.CharField(max_length=500)),
                ('respuesta3', models.CharField(max_length=500)),
                ('respuesta4', models.CharField(max_length=500)),
                ('respuesta5', models.CharField(max_length=500)),
                ('respuesta6', models.CharField(max_length=500)),
                ('respuesta7', models.CharField(max_length=500)),
                ('respuesta8', models.CharField(max_length=500)),
                ('respuesta9', models.CharField(max_length=500)),
                ('respuesta10', models.CharField(max_length=500)),
                ('respuesta11', models.CharField(max_length=500)),
                ('respuesta12', models.CharField(max_length=500)),
                ('respuesta13', models.CharField(max_length=500)),
                ('respuesta14', models.CharField(max_length=500)),
                ('respuesta15', models.CharField(max_length=500)),
                ('respuesta16', models.CharField(max_length=500)),
                ('respuesta17', models.CharField(max_length=500)),
                ('respuesta18', models.CharField(max_length=500)),
                ('respuesta19', models.CharField(max_length=500)),
                ('respuesta20', models.CharField(max_length=500)),
                ('respuesta_hora', models.DateTimeField(auto_now_add=True)),
                ('respuesta_video', models.FileField(blank=True, upload_to='videos/respuestas')),
                ('respuesta_emociones', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
